using System.Net;
using System.Text.Json;
using Dependably.Tests.Infrastructure;

namespace Dependably.Tests.Integration;

[Trait("Category", "Integration")]
public sealed class LicensesControllerTests : IClassFixture<DependablyFactory>, IAsyncLifetime
{
    private readonly DependablyFactory _factory;
    public LicensesControllerTests(DependablyFactory factory) => _factory = factory;
    public Task InitializeAsync() => Task.CompletedTask;
    public Task DisposeAsync() => Task.CompletedTask;

    [Fact]
    public async Task Anonymous_Get_Returns200_WithDevModeStub()
    {
        // notices.json is generated by the Docker build, not by `dotnet run`, so the test
        // harness always hits the dev-mode fallback. That branch must stay stable so the
        // SPA renders its dev-mode hint instead of crashing on a 404.
        using var c = _factory.CreateClient();
        var resp = await c.GetAsync("/api/v1/licenses");

        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
        var doc = await JsonDocument.ParseAsync(await resp.Content.ReadAsStreamAsync());
        Assert.True(doc.RootElement.GetProperty("devModeStub").GetBoolean());
        Assert.Equal(0, doc.RootElement.GetProperty("count").GetInt32());
        Assert.Equal(JsonValueKind.Array, doc.RootElement.GetProperty("components").ValueKind);
    }

    [Fact]
    public async Task Endpoint_IsAnonymous_NotRedirectedToLogin()
    {
        using var c = _factory.CreateClient();
        var resp = await c.GetAsync("/api/v1/licenses");
        Assert.NotEqual(HttpStatusCode.Unauthorized, resp.StatusCode);
        Assert.NotEqual(HttpStatusCode.Forbidden, resp.StatusCode);
    }
}
