using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Xml.Linq;
using Dapper;
using Dependably.Infrastructure;
using Dependably.Protocol;

namespace Dependably.Storage;

/// <summary>
/// Generates the three documents <c>dnf</c>/<c>yum</c> read out of <c>repodata/</c>:
/// <c>repomd.xml</c> (index pointing at the other two), <c>primary.xml</c> (per-package
/// summary, dependencies, file location, sizes, checksums), and a follow-up
/// <c>filelists.xml</c> / <c>other.xml</c> not yet generated by this MVP. Enough to drive
/// <c>dnf repolist</c> + <c>dnf install</c> against an arch-uniform repository.
/// </summary>
public sealed class RpmRepodataService
{
    private readonly IMetadataStore _db;

    public RpmRepodataService(IMetadataStore db) => _db = db;

    /// <summary>
    /// Builds the <c>primary.xml</c> document for one tenant. Streams every published RPM
    /// under that tenant in a single pass — <c>maven-metadata.xml</c>-style live render,
    /// since the rebuild service will cache the compressed result.
    /// </summary>
    public async Task<string> BuildPrimaryAsync(string orgId, CancellationToken ct)
    {
        await using var conn = await _db.OpenAsync(ct);
        // xtenant: explicit org_id filter on the join through packages.
        var rows = (await conn.QueryAsync<RpmPrimaryRow>(
            """
            SELECT p.purl_name AS PurlName,
                   pv.version  AS Version,
                   pv.checksum_sha256 AS Sha256,
                   pv.size_bytes AS SizeBytes,
                   pv.blob_key AS BlobKey,
                   pv.filename AS Filename,
                   rm.rpm_name AS Name,
                   rm.arch     AS Arch,
                   rm.epoch    AS Epoch,
                   rm.rpm_version AS RpmVersion,
                   rm.rpm_release AS RpmRelease,
                   rm.summary  AS Summary,
                   rm.description AS Description,
                   rm.build_host AS BuildHost,
                   rm.build_time AS BuildTime,
                   rm.installed_size AS InstalledSize,
                   rm.archive_size   AS ArchiveSize,
                   rm.rpm_license    AS License,
                   rm.packager       AS Packager,
                   rm.url            AS Url,
                   rm.rpm_group      AS RpmGroup,
                   rm.source_rpm     AS SourceRpm,
                   rm.header_start   AS HeaderStart,
                   rm.header_end     AS HeaderEnd
            FROM package_versions pv
            JOIN packages p ON p.id = pv.package_id
            JOIN rpm_metadata rm ON rm.package_version_id = pv.id
            WHERE p.org_id = @orgId AND p.ecosystem = 'rpm'
            ORDER BY p.purl_name, pv.created_at DESC
            """,
            new { orgId })).ToList();

        XNamespace common = "http://linux.duke.edu/metadata/common";
        XNamespace rpm = "http://linux.duke.edu/metadata/rpm";

        var doc = new XDocument(
            new XDeclaration("1.0", "UTF-8", null),
            new XElement(common + "metadata",
                new XAttribute(XNamespace.Xmlns + "rpm", rpm.NamespaceName),
                new XAttribute("packages", rows.Count),
                rows.Select(r => RenderPackage(r, common, rpm))));

        using var sw = new Utf8StringWriter();
        doc.Save(sw, SaveOptions.None);
        return sw.ToString();
    }

    // XDocument.Save derives the XML declaration's `encoding` from the writer's
    // Encoding property. StringWriter is UTF-16, so saving to it emits
    // <?xml version="1.0" encoding="utf-16"?> even when XDeclaration says UTF-8 —
    // which then mismatches the UTF-8 bytes the controller sends and breaks dnf.
    private sealed class Utf8StringWriter : StringWriter
    {
        public override System.Text.Encoding Encoding => System.Text.Encoding.UTF8;
    }

    /// <summary>
    /// Builds <c>repomd.xml</c> pointing at the just-built <c>primary.xml.gz</c>. SHA-256
    /// + size are computed from the compressed bytes the caller will serve, so the
    /// document the client sees matches what they download.
    /// </summary>
    public static string BuildRepomd(byte[] primaryGz)
    {
        var sha = Convert.ToHexString(SHA256.HashData(primaryGz)).ToLowerInvariant();
        XNamespace repo = "http://linux.duke.edu/metadata/repo";

        var doc = new XDocument(
            new XDeclaration("1.0", "UTF-8", null),
            new XElement(repo + "repomd",
                new XAttribute("revision", DateTimeOffset.UtcNow.ToUnixTimeSeconds()),
                new XElement(repo + "data",
                    new XAttribute("type", "primary"),
                    new XElement(repo + "checksum",
                        new XAttribute("type", "sha256"),
                        sha),
                    new XElement(repo + "location",
                        new XAttribute("href", "repodata/primary.xml.gz")),
                    new XElement(repo + "timestamp", DateTimeOffset.UtcNow.ToUnixTimeSeconds()),
                    new XElement(repo + "size", primaryGz.Length))));

        using var sw = new Utf8StringWriter();
        doc.Save(sw, SaveOptions.None);
        return sw.ToString();
    }

    /// <summary>Gzip-compresses <paramref name="data"/> for repodata file downloads.</summary>
    public static byte[] Gzip(byte[] data)
    {
        using var ms = new MemoryStream();
        using (var gz = new GZipStream(ms, CompressionLevel.Optimal, leaveOpen: true))
            gz.Write(data, 0, data.Length);
        return ms.ToArray();
    }

    private static XElement RenderPackage(RpmPrimaryRow r, XNamespace common, XNamespace rpm)
    {
        return new XElement(common + "package",
            new XAttribute("type", "rpm"),
            new XElement(common + "name", r.Name),
            new XElement(common + "arch", r.Arch),
            new XElement(common + "version",
                new XAttribute("epoch", r.Epoch),
                new XAttribute("ver", r.RpmVersion),
                new XAttribute("rel", r.RpmRelease)),
            new XElement(common + "checksum",
                new XAttribute("type", "sha256"),
                new XAttribute("pkgid", "YES"),
                r.Sha256 ?? ""),
            new XElement(common + "summary", r.Summary ?? ""),
            new XElement(common + "description", r.Description ?? ""),
            new XElement(common + "packager", r.Packager ?? ""),
            new XElement(common + "url", r.Url ?? ""),
            new XElement(common + "time",
                new XAttribute("file", DateTimeOffset.UtcNow.ToUnixTimeSeconds()),
                new XAttribute("build", r.BuildTime ?? 0)),
            new XElement(common + "size",
                new XAttribute("package", r.SizeBytes),
                new XAttribute("installed", r.InstalledSize),
                new XAttribute("archive", r.ArchiveSize)),
            new XElement(common + "location",
                new XAttribute("href", $"packages/{r.Filename}")),
            new XElement(common + "format",
                new XElement(rpm + "license", r.License ?? ""),
                new XElement(rpm + "vendor", ""),
                new XElement(rpm + "group", r.RpmGroup ?? ""),
                new XElement(rpm + "buildhost", r.BuildHost ?? ""),
                new XElement(rpm + "sourcerpm", r.SourceRpm ?? ""),
                new XElement(rpm + "header-range",
                    new XAttribute("start", r.HeaderStart),
                    new XAttribute("end", r.HeaderEnd))));
    }

    // Positional record so Dapper binds via the constructor — avoids S1144/S3459 false
    // positives on per-property setters / unassigned auto-properties.
    // INTEGER columns must bind as long: SQLite returns INTEGER as Int64 and Dapper's
    // constructor binder won't narrow Int64→Int32. (Postgres INTEGER widens cleanly.)
    private sealed record RpmPrimaryRow(
        string PurlName,
        string Version,
        string? Sha256,
        long SizeBytes,
        string BlobKey,
        string? Filename,
        string Name,
        string Arch,
        long Epoch,
        string RpmVersion,
        string RpmRelease,
        string? Summary,
        string? Description,
        string? BuildHost,
        long? BuildTime,
        long InstalledSize,
        long ArchiveSize,
        string? License,
        string? Packager,
        string? Url,
        string? RpmGroup,
        string? SourceRpm,
        long HeaderStart,
        long HeaderEnd);
}
