using System.Text.Json;
using Tomlyn;
using Tomlyn.Model;

namespace Dependably.Protocol;

/// <summary>
/// Parses ecosystem lockfile / requirements formats into a normalised list of
/// <see cref="ManifestEntry"/> records for the manifest-driven import path.
///
/// Supported:
/// <list type="bullet">
///   <item>npm <c>package-lock.json</c> v1 (top-level <c>dependencies</c> tree) and v2/v3
///   (top-level <c>packages</c> map). The lockfile-version field selects which walk to use.</item>
///   <item>pip <c>requirements.txt</c> with pinned <c>name==version</c> lines and optional
///   <c>--hash=sha256:...</c> continuations.</item>
///   <item>pipenv <c>Pipfile.lock</c> — JSON with <c>default</c>/<c>develop</c> maps of
///   name → {<c>version</c> (an exact <c>==</c> pin), <c>hashes</c> (<c>sha256:...</c>)}.</item>
///   <item>poetry <c>poetry.lock</c> — TOML array-of-tables <c>[[package]]</c> with
///   <c>name</c> + <c>version</c>. Poetry records per-file hashes (not a single package
///   hash), so entries carry a null hash and match on name+version.</item>
///   <item>NuGet <c>packages.lock.json</c> — central transitive lock with one entry per
///   resolved (id, version) across all target frameworks.</item>
/// </list>
///
/// Names are normalised to the same form the per-ecosystem validator emits, so manifest
/// entries can match against parsed artefacts without ecosystem-specific reconciliation:
/// pip uses PEP 503, nuget uses lowercase, npm uses raw scope/name.
/// </summary>
public static class ManifestParser
{
    public enum ManifestType { Unknown, NpmPackageLock, PipRequirements, NuGetPackagesLock, PipfileLock, PoetryLock }

    /// <summary>
    /// Detects manifest type from a filename (preferred) and a peek at the content.
    /// Filename takes precedence — operators name these files conventionally.
    /// </summary>
    public static ManifestType Detect(string filename, string content)
    {
        string lower = filename.ToLowerInvariant();
        if (lower.EndsWith("package-lock.json", StringComparison.Ordinal))
        {
            return ManifestType.NpmPackageLock;
        }

        if (lower.EndsWith("packages.lock.json", StringComparison.Ordinal))
        {
            return ManifestType.NuGetPackagesLock;
        }

        if (lower.EndsWith("pipfile.lock", StringComparison.Ordinal))
        {
            return ManifestType.PipfileLock;
        }

        if (lower.EndsWith("poetry.lock", StringComparison.Ordinal))
        {
            return ManifestType.PoetryLock;
        }

        if (lower.EndsWith("requirements.txt", StringComparison.Ordinal))
        {
            return ManifestType.PipRequirements;
        }

        // Content sniff fallback.
        string trimmed = content.TrimStart();
        return trimmed.StartsWith('{')
            ? DetectFromJsonContent(content)
            : trimmed.Length > 0 ? DetectFromTextContent(trimmed) : ManifestType.Unknown;
    }

    // JSON content is disambiguated by its top-level keys.
    private static ManifestType DetectFromJsonContent(string content)
    {
        try
        {
            using var doc = JsonDocument.Parse(content);
            var root = doc.RootElement;
            if (root.TryGetProperty("lockfileVersion", out _))
            {
                return ManifestType.NpmPackageLock;
            }
            // Pipfile.lock has a _meta block alongside default/develop dependency maps and
            // no lockfileVersion — check it before NuGet's dependencies+version shape.
            if (root.TryGetProperty("_meta", out _)
                && (root.TryGetProperty("default", out _) || root.TryGetProperty("develop", out _)))
            {
                return ManifestType.PipfileLock;
            }

            if (root.TryGetProperty("dependencies", out var deps) && deps.ValueKind == JsonValueKind.Object
                && root.TryGetProperty("version", out _))
            {
                return ManifestType.NuGetPackagesLock;
            }
        }
        catch (JsonException) { /* fall through */ }
        return ManifestType.Unknown;
    }

    // poetry.lock is TOML — recognised by its array-of-tables packages or the generator header
    // poetry writes at the top. requirements.txt is the only other plain-text manifest we accept.
    private static ManifestType DetectFromTextContent(string trimmed)
    {
        return trimmed.Contains("[[package]]", StringComparison.Ordinal)
            || trimmed.StartsWith("# This file is automatically generated by Poetry", StringComparison.Ordinal)
            ? ManifestType.PoetryLock
            : ManifestType.PipRequirements;
    }

    public static IReadOnlyList<ManifestEntry> Parse(ManifestType type, string content) => type switch
    {
        ManifestType.NpmPackageLock => ParseNpmPackageLock(content),
        ManifestType.PipRequirements => ParseRequirementsTxt(content),
        ManifestType.NuGetPackagesLock => ParseNuGetPackagesLock(content),
        ManifestType.PipfileLock => ParsePipfileLock(content),
        ManifestType.PoetryLock => ParsePoetryLock(content),
        _ => []
    };

    private static List<ManifestEntry> ParseNpmPackageLock(string json)
    {
        var entries = new List<ManifestEntry>();
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;

        if (LockfileVersion(root) >= 2
            && root.TryGetProperty("packages", out var packages)
            && packages.ValueKind == JsonValueKind.Object)
        {
            // v2/v3: each key is a node_modules path; the empty-string key is the root project.
            foreach (var prop in packages.EnumerateObject())
            {
                var entry = TryReadNpmPackagesEntry(prop);
                if (entry is not null)
                {
                    entries.Add(entry);
                }
            }
        }
        else if (root.TryGetProperty("dependencies", out var deps)
            && deps.ValueKind == JsonValueKind.Object)
        {
            // v1: depth-first walk through the nested dependency tree.
            WalkV1(deps, entries);
        }

        // Dedup: the same (name, version) shows up under multiple paths in v2/v3 and across
        // transitive trees in v1. Keep one entry per coordinate.
        return entries
            .GroupBy(e => (e.Ecosystem, e.Name, e.Version))
            .Select(g => g.First())
            .ToList();
    }

    private static int LockfileVersion(JsonElement root) =>
        root.TryGetProperty("lockfileVersion", out var lv) && lv.ValueKind == JsonValueKind.Number
            ? lv.GetInt32()
            : 1;

    /// <summary>
    /// Reads one entry from the v2/v3 <c>packages</c> map. Returns null when the entry
    /// is the root project (empty key), a non-package path, or is missing a version
    /// (every required field is a "skip on absent" rather than a hard error — partial
    /// lockfiles in the wild stay tolerable).
    /// </summary>
    private static ManifestEntry? TryReadNpmPackagesEntry(JsonProperty prop)
    {
        if (string.IsNullOrEmpty(prop.Name))
        {
            return null;
        }

        string? pkgName = ExtractNpmNameFromPath(prop.Name);
        if (pkgName is null)
        {
            return null;
        }

        if (!prop.Value.TryGetProperty("version", out var ver) || ver.ValueKind != JsonValueKind.String)
        {
            return null;
        }

        string? integrity = prop.Value.TryGetProperty("integrity", out var ig) && ig.ValueKind == JsonValueKind.String
            ? ig.GetString() : null;
        return new ManifestEntry("npm", pkgName, ver.GetString()!, ParseIntegrity(integrity));
    }

    private static void WalkV1(JsonElement deps, List<ManifestEntry> entries)
    {
        foreach (var prop in deps.EnumerateObject())
        {
            if (!prop.Value.TryGetProperty("version", out var ver) || ver.ValueKind != JsonValueKind.String)
            {
                continue;
            }

            string version = ver.GetString()!;
            string? integrity = prop.Value.TryGetProperty("integrity", out var ig) && ig.ValueKind == JsonValueKind.String
                ? ig.GetString() : null;
            entries.Add(new ManifestEntry("npm", prop.Name, version, ParseIntegrity(integrity)));
            if (prop.Value.TryGetProperty("dependencies", out var nested) && nested.ValueKind == JsonValueKind.Object)
            {
                WalkV1(nested, entries);
            }
        }
    }

    /// <summary>
    /// "node_modules/lodash" → "lodash". "node_modules/@scope/name" → "@scope/name".
    /// Skips entries that don't start with node_modules/ (e.g. workspaces, root references).
    /// </summary>
    private static string? ExtractNpmNameFromPath(string path)
    {
        const string prefix = "node_modules/";
        if (!path.StartsWith(prefix, StringComparison.Ordinal))
        {
            return null;
        }

        string rest = path[prefix.Length..];
        // Pick the last occurrence so nested dependencies (node_modules/a/node_modules/b) still
        // resolve to the leaf package name.
        int idx = rest.LastIndexOf(prefix, StringComparison.Ordinal);
        if (idx >= 0)
        {
            rest = rest[(idx + prefix.Length)..];
        }

        return rest.Length == 0 ? null : rest;
    }

    private static List<ManifestEntry> ParseRequirementsTxt(string content)
    {
        var entries = new List<ManifestEntry>();
        // Stitch line continuations: requirements.txt allows trailing backslash to extend a
        // line, particularly for hash continuations (--hash=sha256:...). Normalise first.
        string stitched = content.Replace("\\\r\n", " ").Replace("\\\n", " ");
        foreach (string rawLine in stitched.Split('\n'))
        {
            var entry = TryParseRequirementLine(rawLine);
            if (entry is not null)
            {
                entries.Add(entry);
            }
        }
        return entries;
    }

    /// <summary>
    /// Parses one requirements.txt line, returning null for blank/comment/option lines or
    /// any pinning shape we don't recognise (e.g. <c>~=</c>, <c>&gt;=</c>; we only match
    /// strict <c>==</c> pins because looser specifiers can't be matched to a single
    /// uploaded artefact). Strips trailing comments and PEP 508 environment markers.
    /// </summary>
    private static ManifestEntry? TryParseRequirementLine(string rawLine)
    {
        string line = rawLine.Trim();
        if (line.Length == 0 || line.StartsWith('#') || line.StartsWith('-'))
        {
            return null;
        }

        int hashIdx = line.IndexOf('#');
        if (hashIdx > 0)
        {
            line = line[..hashIdx].Trim();
        }

        int semiIdx = line.IndexOf(';');
        if (semiIdx >= 0)
        {
            line = line[..semiIdx].Trim();
        }

        string[] parts = line.Split("==", 2, StringSplitOptions.None);
        if (parts.Length != 2)
        {
            return null;
        }

        string name = parts[0].Trim();
        string rhs = parts[1].Trim();
        int ws = rhs.IndexOfAny([' ', '\t']);
        string version = ws < 0 ? rhs : rhs[..ws].Trim();
        string hashes = ws < 0 ? "" : rhs[ws..];

        return new ManifestEntry(
            "pypi", PyPiArtifactValidator.Normalize(name), version, ExtractFirstSha256Hash(hashes));
    }

    /// <summary>
    /// Pulls the first <c>--hash=sha256:&lt;hex&gt;</c> token out of a requirements.txt line's
    /// trailing hash clauses. Returns null if no sha256 hash is present (md5/sha1 are not
    /// recorded — we hash uploads with sha256 and don't try to match other algorithms).
    /// </summary>
    private static string? ExtractFirstSha256Hash(string hashes)
    {
        const string hashPrefix = "--hash=sha256:";
        int hashStart = hashes.IndexOf(hashPrefix, StringComparison.Ordinal);
        if (hashStart < 0)
        {
            return null;
        }

        string hashRest = hashes[(hashStart + hashPrefix.Length)..];
        int hashEnd = hashRest.IndexOfAny([' ', '\t', '-']);
        return hashEnd < 0 ? hashRest.Trim() : hashRest[..hashEnd].Trim();
    }

    /// <summary>
    /// Parses a pipenv <c>Pipfile.lock</c> (JSON). The <c>default</c> and <c>develop</c> objects
    /// each map a package name to <c>{ "version": "==X", "hashes": ["sha256:..."] }</c>. Only
    /// exact <c>==</c> pins are kept (a single artefact can't be matched to a looser specifier),
    /// matching the requirements.txt rule. The first <c>sha256:</c> hash is recorded as hex.
    /// </summary>
    private static List<ManifestEntry> ParsePipfileLock(string json)
    {
        var entries = new List<ManifestEntry>();
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;
        foreach (string section in (string[])["default", "develop"])
        {
            if (!root.TryGetProperty(section, out var deps) || deps.ValueKind != JsonValueKind.Object)
            {
                continue;
            }

            foreach (var pkg in deps.EnumerateObject())
            {
                var entry = TryReadPipfileEntry(pkg);
                if (entry is not null)
                {
                    entries.Add(entry);
                }
            }
        }
        return entries
            .GroupBy(e => (e.Ecosystem, e.Name, e.Version))
            .Select(g => g.First())
            .ToList();
    }

    /// <summary>
    /// Reads one entry from a Pipfile.lock <c>default</c>/<c>develop</c> map. Returns null for
    /// entries without an exact <c>==</c> version pin (e.g. vcs/path deps or range specifiers).
    /// </summary>
    private static ManifestEntry? TryReadPipfileEntry(JsonProperty pkg)
    {
        if (pkg.Value.ValueKind != JsonValueKind.Object)
        {
            return null;
        }

        if (!pkg.Value.TryGetProperty("version", out var ver) || ver.ValueKind != JsonValueKind.String)
        {
            return null;
        }

        string version = ver.GetString()!.Trim();
        if (!version.StartsWith("==", StringComparison.Ordinal))
        {
            return null;
        }

        version = version[2..].Trim();
        if (version.Length == 0)
        {
            return null;
        }

        string? sha256 = null;
        if (pkg.Value.TryGetProperty("hashes", out var hashes) && hashes.ValueKind == JsonValueKind.Array)
        {
            foreach (var h in hashes.EnumerateArray())
            {
                if (h.ValueKind != JsonValueKind.String)
                {
                    continue;
                }

                const string prefix = "sha256:";
                string s = h.GetString()!;
                if (s.StartsWith(prefix, StringComparison.Ordinal)) { sha256 = s[prefix.Length..].Trim(); break; }
            }
        }
        return new ManifestEntry("pypi", PyPiArtifactValidator.Normalize(pkg.Name), version, sha256);
    }

    /// <summary>
    /// Parses a poetry <c>poetry.lock</c> (TOML). Each <c>[[package]]</c> table carries
    /// <c>name</c> and <c>version</c>. Entries without a PEP 440-shaped version (vcs/path/url
    /// source deps) are skipped. Poetry stores per-file hashes rather than a single package
    /// hash, so entries carry a null hash and match on name+version.
    /// </summary>
    private static List<ManifestEntry> ParsePoetryLock(string toml)
    {
        var entries = new List<ManifestEntry>();
        var model = TomlSerializer.Deserialize<TomlTable>(toml);
        if (model is not null && model.TryGetValue("package", out object? pkgValue) && pkgValue is TomlTableArray packages)
        {
            foreach (var pkg in packages)
            {
                if (!pkg.TryGetValue("name", out object? nameObj) || nameObj is not string name)
                {
                    continue;
                }

                if (!pkg.TryGetValue("version", out object? verObj) || verObj is not string version)
                {
                    continue;
                }

                version = version.Trim();
                if (!PyPiArtifactValidator.IsPep440Version(version))
                {
                    continue;
                }

                entries.Add(new ManifestEntry("pypi", PyPiArtifactValidator.Normalize(name), version, null));
            }
        }
        return entries
            .GroupBy(e => (e.Ecosystem, e.Name, e.Version))
            .Select(g => g.First())
            .ToList();
    }

    private static List<ManifestEntry> ParseNuGetPackagesLock(string json)
    {
        var entries = new List<ManifestEntry>();
        using var doc = JsonDocument.Parse(json);
        if (!doc.RootElement.TryGetProperty("dependencies", out var byFramework)
            || byFramework.ValueKind != JsonValueKind.Object)
        {
            return entries;
        }

        foreach (var fwValue in byFramework.EnumerateObject()
                                            .Where(fw => fw.Value.ValueKind == JsonValueKind.Object)
                                            .Select(fw => fw.Value))
        {
            foreach (var pkg in fwValue.EnumerateObject())
            {
                var entry = TryReadNuGetPackageEntry(pkg);
                if (entry is not null)
                {
                    entries.Add(entry);
                }
            }
        }
        return entries
            .GroupBy(e => (e.Ecosystem, e.Name, e.Version))
            .Select(g => g.First())
            .ToList();
    }

    /// <summary>
    /// Reads one entry from a <c>packages.lock.json</c> framework block. Returns null if
    /// the entry is not a project dependency (e.g. <c>type:Project</c>) or is missing
    /// the <c>resolved</c> version we need to match an uploaded artefact.
    /// </summary>
    private static ManifestEntry? TryReadNuGetPackageEntry(JsonProperty pkg)
    {
        if (pkg.Value.ValueKind != JsonValueKind.Object)
        {
            return null;
        }

        if (!pkg.Value.TryGetProperty("resolved", out var ver) || ver.ValueKind != JsonValueKind.String)
        {
            return null;
        }

        string? sha = pkg.Value.TryGetProperty("contentHash", out var ch) && ch.ValueKind == JsonValueKind.String
            ? ch.GetString() : null;
        return new ManifestEntry("nuget", pkg.Name.ToLowerInvariant(), ver.GetString()!, sha);
    }

    /// <summary>
    /// npm integrity strings are in subresource-integrity format ("sha512-..." / "sha256-...").
    /// We only record sha256 since that's what we hash uploads with; everything else is null.
    /// </summary>
    private static string? ParseIntegrity(string? integrity)
    {
        if (string.IsNullOrEmpty(integrity))
        {
            return null;
        }

        const string prefix = "sha256-";
        if (!integrity.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        string b64 = integrity[prefix.Length..];
        try { return Convert.ToHexString(Convert.FromBase64String(b64)).ToLowerInvariant(); }
        catch { return null; }
    }
}

/// <summary>One package coordinate from a manifest. Matched against an uploaded artefact.</summary>
public sealed record ManifestEntry(string Ecosystem, string Name, string Version, string? Sha256);
