<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <InvariantGlobalization>false</InvariantGlobalization>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <Content Remove="appsettings.Development.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dependably.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dependably.Core\Dependably.Core.csproj" />
    <ProjectReference Include="..\Dependably.Management\Dependably.Management.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Dependably.Management\wwwroot\**"
             Link="wwwroot\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="SecurityCodeScan.VS2019" Version="5.6.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
      <DevelopmentDependency>true</DevelopmentDependency>
    </PackageReference>
  </ItemGroup>

</Project>
