using System.Net;
using Dependably.Protocol;
using Microsoft.Extensions.Logging.Abstractions;
using WireMock.RequestBuilders;
using WireMock.ResponseBuilders;
using WireMock.Server;

namespace Dependably.Tests.Unit.Protocol;

/// <summary>
/// Regression coverage for #609: CVSS v4.0 base-score support in <see cref="OsvScoring"/>, plus
/// the entry-selection fix and online/offline parity it depends on. The 42 curated vectors in
/// <see cref="CuratedVectors"/> were generated by running FIRST.org's own reference calculator
/// (BSD-2-Clause, github.com/FIRSTdotorg/cvss-v4-calculator) and cross-checked against an
/// independent CVSS v4 implementation — see the port's own attribution header in
/// <c>OsvScoring.Cvss4.cs</c>.
/// </summary>
[Trait("Category", "Unit")]
public sealed class OsvScoringCvss4Tests
{
    public static IEnumerable<object[]> CuratedVectors =>
    [
        ["CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:L/SI:H/SA:N", 9.0],
        ["CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:N/VI:L/VA:H/SC:L/SI:H/SA:N", 9.0],
        ["CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:H/VI:H/VA:L/SC:L/SI:L/SA:L", 9.2],
        ["CVSS:4.0/AV:A/AC:L/AT:N/PR:N/UI:A/VC:H/VI:H/VA:H/SC:H/SI:N/SA:L", 9.2],
        ["CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H", 10.0],
        ["CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:L/VI:L/VA:H/SC:L/SI:L/SA:H", 9.1],
        ["CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:H/VA:L/SC:L/SI:H/SA:N", 9.0],
        ["CVSS:4.0/AV:A/AC:L/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:L/SI:H/SA:L", 9.3],
        ["CVSS:4.0/AV:L/AC:L/AT:N/PR:H/UI:N/VC:H/VI:H/VA:H/SC:H/SI:N/SA:N", 9.2],
        ["CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:H/VA:N/SC:L/SI:L/SA:H", 9.1],
        ["CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:A/VC:H/VI:N/VA:N/SC:L/SI:H/SA:N", 8.2],
        ["CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:P/VC:H/VI:H/VA:N/SC:H/SI:H/SA:H", 7.2],
        ["CVSS:4.0/AV:A/AC:L/AT:P/PR:N/UI:P/VC:N/VI:L/VA:H/SC:N/SI:L/SA:H", 7.0],
        ["CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:A/VC:H/VI:N/VA:H/SC:N/SI:H/SA:N", 7.0],
        ["CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:N/VC:H/VI:L/VA:L/SC:H/SI:L/SA:L", 8.5],
        ["CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:P/VC:L/VI:L/VA:H/SC:N/SI:H/SA:H", 8.3],
        ["CVSS:4.0/AV:A/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:H/SC:L/SI:H/SA:N", 8.4],
        ["CVSS:4.0/AV:N/AC:H/AT:P/PR:H/UI:A/VC:L/VI:H/VA:H/SC:L/SI:N/SA:H", 7.0],
        ["CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:N/VC:H/VI:N/VA:N/SC:H/SI:N/SA:N", 8.2],
        ["CVSS:4.0/AV:N/AC:H/AT:N/PR:L/UI:N/VC:N/VI:H/VA:N/SC:H/SI:H/SA:N", 7.1],
        ["CVSS:4.0/AV:N/AC:L/AT:P/PR:H/UI:N/VC:N/VI:H/VA:N/SC:N/SI:H/SA:N", 6.9],
        ["CVSS:4.0/AV:L/AC:H/AT:N/PR:L/UI:A/VC:H/VI:N/VA:L/SC:L/SI:H/SA:L", 5.8],
        ["CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:A/VC:L/VI:L/VA:N/SC:H/SI:L/SA:N", 6.0],
        ["CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:H", 6.9],
        ["CVSS:4.0/AV:P/AC:H/AT:N/PR:L/UI:A/VC:L/VI:L/VA:H/SC:L/SI:H/SA:H", 6.0],
        ["CVSS:4.0/AV:L/AC:H/AT:N/PR:H/UI:N/VC:N/VI:N/VA:L/SC:H/SI:L/SA:N", 4.3],
        ["CVSS:4.0/AV:N/AC:H/AT:N/PR:L/UI:P/VC:N/VI:H/VA:L/SC:N/SI:N/SA:N", 5.9],
        ["CVSS:4.0/AV:A/AC:L/AT:N/PR:H/UI:P/VC:L/VI:L/VA:L/SC:H/SI:L/SA:L", 4.4],
        ["CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:A/VC:L/VI:N/VA:H/SC:L/SI:H/SA:H", 5.9],
        ["CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:A/VC:L/VI:H/VA:L/SC:N/SI:L/SA:N", 4.4],
        ["CVSS:4.0/AV:P/AC:L/AT:P/PR:L/UI:P/VC:L/VI:N/VA:N/SC:N/SI:N/SA:L", 1.0],
        ["CVSS:4.0/AV:A/AC:L/AT:N/PR:L/UI:P/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N", 2.4],
        ["CVSS:4.0/AV:P/AC:L/AT:P/PR:L/UI:P/VC:L/VI:L/VA:L/SC:L/SI:L/SA:H", 2.1],
        ["CVSS:4.0/AV:L/AC:H/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:L/SA:N", 2.1],
        ["CVSS:4.0/AV:A/AC:L/AT:N/PR:L/UI:P/VC:L/VI:L/VA:L/SC:L/SI:L/SA:L", 2.4],
        ["CVSS:4.0/AV:A/AC:H/AT:P/PR:H/UI:P/VC:N/VI:L/VA:N/SC:L/SI:N/SA:L", 1.0],
        ["CVSS:4.0/AV:N/AC:H/AT:P/PR:L/UI:P/VC:L/VI:L/VA:N/SC:L/SI:L/SA:L", 2.1],
        ["CVSS:4.0/AV:P/AC:L/AT:P/PR:L/UI:N/VC:L/VI:L/VA:L/SC:L/SI:N/SA:H", 2.0],
        ["CVSS:4.0/AV:P/AC:H/AT:N/PR:H/UI:A/VC:N/VI:N/VA:L/SC:L/SI:L/SA:H", 2.1],
        ["CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:A/VC:L/VI:N/VA:L/SC:N/SI:L/SA:N", 1.0],
        ["CVSS:4.0/AV:P/AC:H/AT:P/PR:H/UI:A/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N", 0.0],
        ["CVSS:4.0/AV:L/AC:L/AT:N/PR:H/UI:A/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N", 0.0],
    ];

    [Theory]
    [MemberData(nameof(CuratedVectors))]
    public void ParseCvssBaseScore_Cvss4CuratedVectors_MatchReferenceCalculator(string vector, double expectedScore)
    {
        (double? score, string? severity) = OsvScoring.ParseCvssBaseScore(vector);

        Assert.Equal(expectedScore, score);
        Assert.Equal(OsvScoring.CvssScoreToSeverity(expectedScore), severity);
    }

    [Fact]
    public void ParseCvssBaseScore_Cvss4_MalformedVector_ReturnsNull()
    {
        var (score, severity) = OsvScoring.ParseCvssBaseScore("CVSS:4.0/AV:N/AC:L");

        Assert.Null(score);
        Assert.Null(severity);
    }

    // ── The real EEF-shaped defect: no database_specific.severity fallback ─────

    private const string Cvss4OnlyAdvisoryJson = """
        {
          "id": "EEF-CVE-2026-32689",
          "summary": "phoenix vulnerable to something",
          "affected": [{
            "package": { "ecosystem": "npm", "name": "acme" },
            "versions": ["1.0.0"]
          }],
          "severity": [{ "type": "CVSS_V4", "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H" }],
          "database_specific": { "cwe_ids": ["CWE-79"], "capec_ids": [], "cpe_ids": [] }
        }
        """;

    [Fact]
    public async Task LocalOsvSource_Cvss4OnlyAdvisory_NoDatabaseSpecificSeverity_ProducesExactScoreAndSeverity()
    {
        string dir = Path.Combine(Path.GetTempPath(), "osvtest_cvss4_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            File.WriteAllText(Path.Combine(dir, "EEF-CVE-2026-32689.json"), Cvss4OnlyAdvisoryJson);
            var src = new LocalOsvSource(dir, NullLogger<LocalOsvSource>.Instance);

            var hits = await src.QueryAsync("pkg:npm/acme@1.0.0");

            Assert.Single(hits);
            // Exact value, not merely non-null — an EEF-shaped advisory carries no
            // database_specific.severity fallback, so this arm was fully inert before #609.
            Assert.Equal(10.0, hits[0].CvssScore);
            Assert.Equal("CRITICAL", hits[0].Severity);
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    // ── Entry-selection defect: CVSS_V4 listed before a parseable CVSS_V3 ───────

    private const string Cvss4FirstUnparseable_Cvss3Second_AdvisoryJson = """
        {
          "id": "GHSA-entry-order",
          "summary": "dual-severity advisory",
          "affected": [{
            "package": { "ecosystem": "npm", "name": "acme" },
            "versions": ["1.0.0"]
          }],
          "severity": [
            { "type": "CVSS_V4", "score": "CVSS:4.0/AV:N/AC:L" },
            { "type": "CVSS_V3", "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H" }
          ]
        }
        """;

    [Fact]
    public async Task LocalOsvSource_Cvss4ListedFirstButUnparseable_FallsBackToParseableCvss3()
    {
        string dir = Path.Combine(Path.GetTempPath(), "osvtest_entryorder_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            File.WriteAllText(Path.Combine(dir, "GHSA-entry-order.json"), Cvss4FirstUnparseable_Cvss3Second_AdvisoryJson);
            var src = new LocalOsvSource(dir, NullLogger<LocalOsvSource>.Instance);

            var hits = await src.QueryAsync("pkg:npm/acme@1.0.0");

            Assert.Single(hits);
            // The malformed CVSS_V4 entry is listed first; the advisory must not lose its
            // score because of that — the parseable CVSS_V3 entry is used instead.
            Assert.Equal(9.8, hits[0].CvssScore);
            Assert.Equal("CRITICAL", hits[0].Severity);
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    // ── Online/offline parity: same raw advisory JSON, same result, both paths ─

    [Fact]
    public async Task OsvClient_And_LocalOsvSource_ProduceIdenticalScoreAndSeverity_ForSameAdvisory()
    {
        // LocalOsvSource: file-dump path.
        string dir = Path.Combine(Path.GetTempPath(), "osvtest_parity_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        OsvAdvisory offlineHit;
        try
        {
            File.WriteAllText(Path.Combine(dir, "EEF-CVE-2026-32689.json"), Cvss4OnlyAdvisoryJson);
            var localSource = new LocalOsvSource(dir, NullLogger<LocalOsvSource>.Instance);
            var offlineHits = await localSource.QueryAsync("pkg:npm/acme@1.0.0");
            Assert.Single(offlineHits);
            offlineHit = offlineHits[0];
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }

        // OsvClient: live-HTTP path, served by WireMock with the exact same advisory body.
        using var server = WireMockServer.Start();
        try
        {
            server.Given(Request.Create().WithPath("/query").UsingPost())
                .RespondWith(Response.Create().WithStatusCode(HttpStatusCode.OK)
                    .WithBody($$"""{"vulns":[{{Cvss4OnlyAdvisoryJson}}]}"""));

            var client = new OsvClient(
                new SingleHandlerFactory(server.Urls[0] + "/"), NullLogger<OsvClient>.Instance);
            var onlineHits = await client.QueryAsync("pkg:npm/acme@1.0.0");

            Assert.Single(onlineHits);
            var onlineHit = onlineHits[0];

            Assert.Equal(offlineHit.CvssScore, onlineHit.CvssScore);
            Assert.Equal(offlineHit.Severity, onlineHit.Severity);
            // Pin the actual value too — a pair of nulls on both sides would trivially "agree".
            Assert.Equal(10.0, onlineHit.CvssScore);
            Assert.Equal("CRITICAL", onlineHit.Severity);
        }
        finally
        {
            server.Stop();
        }
    }

    /// <summary>
    /// Minimal IHttpClientFactory returning a single HttpClient whose BaseAddress points at the
    /// WireMock server (mirrors how OsvClient is wired in Program.cs).
    /// </summary>
    private sealed class SingleHandlerFactory : IHttpClientFactory
    {
        private readonly HttpClient _client;
        public SingleHandlerFactory(string baseUrl) =>
            _client = new HttpClient { BaseAddress = new Uri(baseUrl) };
        public HttpClient CreateClient(string name) => _client;
    }
}
